-- MySQL Script generated by MySQL Workbench
-- seg 28 jun 2021 00:57:00
-- Model: GClinic    Version: 0.1

-- Modelagem do banco de dados GClinic.

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gclinic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gclinic` ;

-- -----------------------------------------------------
-- Schema gclinic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gclinic` DEFAULT CHARACTER SET utf8mb4 ;
USE `gclinic` ;

-- -----------------------------------------------------
-- Table `gclinic`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`Address` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`Address` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_provider` INT UNSIGNED NOT NULL,
  `address` VARCHAR(45) NULL,
  `district` VARCHAR(20) NULL,
  `city` VARCHAR(20) NULL,
  `uf` CHAR(2) NULL,
  `cep` VARCHAR(10) NULL,
  `nation` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_idProvider` (`id_provider` ASC),
  CONSTRAINT `FK_Address_id_provider`
    FOREIGN KEY (`id_provider`)
    REFERENCES `gclinic`.`Providers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gclinic`.`BankAccounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`BankAccounts` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`BankAccounts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_representative` INT(10) UNSIGNED NOT NULL,
  `bank` VARCHAR(45) NULL,
  `agency` VARCHAR(45) NULL,
  `account` VARCHAR(45) NULL,
  `holder` VARCHAR(45) NULL,
  `owner` ENUM('P', 'R') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_bank_account_providers_idx` (`id_representative` ASC),
  CONSTRAINT `FK_BankAccounts_id_representative`
    FOREIGN KEY (`id_representative`)
    REFERENCES `gclinic`.`Representatives` (`id_provider`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gclinic`.`bills_to_receive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`bills_to_receive` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`bills_to_receive` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `receive_venc` DATE NULL DEFAULT NULL,
  `receive_date_pay` DATE NULL DEFAULT NULL,
  `receive_cat` VARCHAR(45) NULL DEFAULT NULL,
  `receive_desc` VARCHAR(45) NULL DEFAULT NULL,
  `receive_val` DECIMAL(7,2) NULL DEFAULT 0.00,
  `receive_created` DATETIME NOT NULL,
  `receive_modified` DATETIME NULL DEFAULT NULL,
  `receive_status` ENUM('1', '2') NULL DEFAULT '2',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gclinic`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`calendar` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`calendar` (
  `calendar_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `calendar_start` VARCHAR(15) NOT NULL,
  `calendar_end` VARCHAR(15) NOT NULL,
  `calendar_start_normal` VARCHAR(50) NOT NULL,
  `calendar_end_normal` VARCHAR(45) NOT NULL,
  `calendar_class` VARCHAR(45) NOT NULL DEFAULT 'event-important',
  `calendar_proc` VARCHAR(45) NOT NULL,
  `calendar_pat` VARCHAR(45) NOT NULL,
  `calendar_desc` TEXT NOT NULL,
  PRIMARY KEY (`calendar_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Tabela agenda de usuários.';


-- -----------------------------------------------------
-- Table `gclinic`.`cash_flow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`cash_flow` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`cash_flow` (
  `flow_id` INT(11) NOT NULL AUTO_INCREMENT,
  `flow_venc` DATE NULL DEFAULT NULL,
  `flow_date_pay` DATE NULL DEFAULT NULL,
  `flow_cat` VARCHAR(45) NULL DEFAULT NULL,
  `flow_desc` VARCHAR(45) NULL DEFAULT NULL,
  `flow_val` DECIMAL(7,2) NULL DEFAULT 0.00,
  `flow_created` DATETIME NOT NULL,
  `flow_modified` DATETIME NULL DEFAULT NULL,
  `flow_status` ENUM('1', '2') NULL DEFAULT '2',
  PRIMARY KEY (`flow_id`),
  UNIQUE INDEX `tipo_unitario_id_UNIQUE` (`flow_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gclinic`.`checks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`checks` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`checks` (
  `checks_id` INT(11) NOT NULL AUTO_INCREMENT,
  `checks_holder` VARCHAR(45) NULL DEFAULT '2',
  `checks_val` DECIMAL(7,2) NULL DEFAULT 0.00,
  `checks_cod` VARCHAR(45) NULL DEFAULT '0.00',
  `checks_bank` VARCHAR(45) NULL DEFAULT NULL,
  `checks_agency` VARCHAR(45) NULL DEFAULT NULL,
  `checks_date` DATE NULL DEFAULT NULL,
  `checks_received` VARCHAR(45) NULL DEFAULT NULL,
  `checks_forwarded` VARCHAR(45) NULL DEFAULT NULL,
  `checks_created` DATETIME NOT NULL,
  `checks_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`checks_id`),
  UNIQUE INDEX `tipo_unitario_id_UNIQUE` (`checks_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gclinic`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`company` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`company` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `empresa_name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela clinica onde ficara armazendo o nome da clinica e seu respectivo id associado a tabela users';


-- -----------------------------------------------------
-- Table `gclinic`.`Contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`Contacts` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`Contacts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_provider` INT(10) UNSIGNED NOT NULL,
  `phone` VARCHAR(20) NULL,
  `type` ENUM('C', 'T') NOT NULL,
  `owner` ENUM('P', 'R') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Contacts_id_provider2_idx` (`id_provider` ASC),
  CONSTRAINT `FK_Contacts_id_provider_p`
    FOREIGN KEY (`id_provider`)
    REFERENCES `gclinic`.`Providers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contacts_id_provider_r`
    FOREIGN KEY (`id_provider`)
    REFERENCES `gclinic`.`Representatives` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gclinic`.`convenant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`convenant` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`convenant` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Campo ID convênio',
  `name` VARCHAR(45) NOT NULL COMMENT 'Nome do fornecedor / Empresa',
  `cpf_cnpj` VARCHAR(45) NOT NULL COMMENT 'CPF ou CNPJ do fornecedor',
  `rs` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Razão Social do fornecedor.',
  `at` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor ará de atuação',
  `covenant_end` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Endereço do fornecedor',
  `covenant_district` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Bairro',
  `covenant_city` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Cidade',
  `covenant_uf` CHAR(2) NULL DEFAULT NULL COMMENT 'Estado UF',
  `covenant_cep` VARCHAR(45) NULL DEFAULT NULL COMMENT 'CEP do fornecedor',
  `covenant_nation` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Pais / Nação',
  `covenant_cel` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Celular',
  `covenant_tel_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Telefone 1',
  `covenant_tel_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Telefone 2',
  `covenant_insc_uf` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Inscrição Estadual',
  `covenant_web_url` VARCHAR(45) NULL DEFAULT NULL COMMENT 'WebSite - do fornecedor',
  `covenant_sit` CHAR(8) NOT NULL DEFAULT 'active',
  `covenant_email` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Email do fornecedor\\n',
  `covenant_rep_name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Nome do Representante - Pessoa de Contato\\n',
  `covenant_rep_nick` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Informações do Representante - Pessoa de Contato',
  `covenant_rep_cel` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Informações do Representante - Pessoa de Contato',
  `covenant_rep_tel_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Informações do Representante - Pessoa de Contato',
  `covenant_rep_tel_2` VARCHAR(45) NULL DEFAULT NULL,
  `covenant_rep_email` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Informações do Representante - Pessoa de Contato',
  `covenant_banco_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_agencia_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_conta_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_titular_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_banco_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_agencia_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_conta_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_titular_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_obs` TEXT NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `covenant_created` DATETIME NOT NULL COMMENT 'Armazena a data de criação do registro',
  `covenant_modified` DATETIME NULL DEFAULT NULL COMMENT 'Armazena a data de modificação do registro',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `covenant_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gclinic`.`fees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`fees` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`fees` (
  `fees_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fees_cod` VARCHAR(45) NULL DEFAULT NULL,
  `fees_proc` VARCHAR(45) NULL DEFAULT NULL,
  `fees_cat` VARCHAR(45) NULL DEFAULT NULL,
  `fees_val_real` VARCHAR(45) NULL DEFAULT NULL,
  `fees_desc` VARCHAR(45) NULL DEFAULT NULL,
  `fees_val_final` VARCHAR(45) NULL DEFAULT NULL,
  `fees_obs` TEXT NULL DEFAULT NULL COMMENT 'Campo destinado a armazenar informações extra sobre o registro.',
  `fees_created` DATETIME NOT NULL COMMENT 'Armazena a data de criação do registro',
  `fees_modified` DATETIME NULL DEFAULT NULL COMMENT 'Armazena a data de modificação do registro',
  PRIMARY KEY (`fees_id`),
  UNIQUE INDEX `fees_id_UNIQUE` (`fees_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela de honorários faz referência a tabela de convênios.';


-- -----------------------------------------------------
-- Table `gclinic`.`laboratory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`laboratory` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`laboratory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Nome laboratório / Empresa',
  `cpf_cnpj` VARCHAR(45) NULL DEFAULT NULL COMMENT 'CPF ou CNPJ do fornecedor',
  `rs` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Razão Social do fornecedor.',
  `at` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor ará de atuação',
  `address` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Endereço do fornecedor',
  `district` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Bairro',
  `city` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Cidade',
  `cep` VARCHAR(45) NULL DEFAULT NULL COMMENT 'CEP do fornecedor',
  `uf` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Estado UF',
  `nation` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Pais / Nação',
  `laboratory_insc_uf` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Inscrição Estadual',
  `laboratory_email` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Email do fornecedor\\n',
  `laboratory_web_url` VARCHAR(45) NULL DEFAULT NULL COMMENT 'WebSite - do fornecedor',
  `laboratory_sit` CHAR(8) NOT NULL DEFAULT 'active',
  `laboratory_conta_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `laboratory_rep_nome` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Nome do Representante - Pessoa de Contato\\n',
  `laboratory_rep_apelido` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Informações do Representante - Pessoa de Contato',
  `laboratory_rep_email` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Informações do Representante - Pessoa de Contato',
  `laboratory_rep_cel` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Informações do Representante - Pessoa de Contato',
  `laboratory_rep_tel_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Informações do Representante - Pessoa de Contato',
  `laboratory_rep_tel_2` VARCHAR(45) NULL DEFAULT NULL,
  `laboratory_banco_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `laboratory_agencia_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `laboratory_conta_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `laboratory_titular_1` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `laboratory_banco_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `laboratory_agencia_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `laboratory_titular_2` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias',
  `laboratory_created` DATETIME NULL DEFAULT NULL COMMENT 'Armazena a data de criação do registro',
  `laboratory_modified` DATETIME NULL DEFAULT NULL COMMENT 'Armazena a data de modificação do registro',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gclinic`.`login_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`login_attempts` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`login_attempts` (
  `login_attempts_id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`login_attempts_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gclinic`.`Patrimony`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`Patrimony` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`Patrimony` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `acquisition_date` DATE NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `provider` VARCHAR(45) NULL DEFAULT NULL,
  `dimension` VARCHAR(45) NULL DEFAULT NULL,
  `sector` VARCHAR(45) NULL DEFAULT NULL,
  `value` DECIMAL(10,2) NULL DEFAULT 0.00,
  `warranty` VARCHAR(45) NULL DEFAULT NULL,
  `quantity` VARCHAR(45) NULL DEFAULT NULL,
  `receipt` VARCHAR(45) NULL DEFAULT NULL,
  `situation` CHAR(8) NOT NULL DEFAULT 'active',
  `observation` LONGTEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela referente a Patrimônio';


-- -----------------------------------------------------
-- Table `gclinic`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`payments` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`payments` (
  `payments_id` INT(11) NOT NULL AUTO_INCREMENT,
  `payments_venc` DATE NULL DEFAULT NULL,
  `payments_date_pay` DATE NULL DEFAULT NULL,
  `payments_cat` VARCHAR(45) NULL DEFAULT NULL,
  `payments_desc` VARCHAR(45) NULL DEFAULT NULL,
  `payments_val` DECIMAL(7,2) NULL DEFAULT 0.00,
  `payments_created` DATETIME NOT NULL,
  `payments_modified` DATETIME NULL DEFAULT NULL,
  `payments_status` ENUM('1', '2') NULL DEFAULT '2',
  PRIMARY KEY (`payments_id`),
  UNIQUE INDEX `tipo_unitario_id_UNIQUE` (`payments_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gclinic`.`Providers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`Providers` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`Providers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID do fornecedor',
  `name` VARCHAR(45) NOT NULL COMMENT 'Nome do fornecedor / Empresa',
  `cpf_cnpj` VARCHAR(45) NULL DEFAULT NULL COMMENT 'CPF ou CNPJ do fornecedor',
  `razao_social` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Razão Social do fornecedor.',
  `occupation_area` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor área de atuação.',
  `insc_uf` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor inscrição Estadual.',
  `web_url` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fornecedor WebSite',
  `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active' COMMENT 'Fornecedor situação.',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Email do fornecedor\\n',
  `obs` TEXT NULL DEFAULT NULL COMMENT 'Fornecedor informações bancárias - Observações',
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gclinic`.`query_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`query_data` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`query_data` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `querycount` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gclinic`.`recoveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`recoveries` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`recoveries` (
  `recovery_id` INT(11) NOT NULL AUTO_INCREMENT,
  `recovery_token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `recovery_status` INT(11) NOT NULL,
  PRIMARY KEY (`recovery_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gclinic`.`Representatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`Representatives` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`Representatives` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_provider` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC, `id_provider` ASC),
  CONSTRAINT `FK_Representatives_id_provider`
    FOREIGN KEY (`id_provider`)
    REFERENCES `gclinic`.`Providers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gclinic`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`roles` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`roles` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_level` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gclinic`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`stock` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`stock` (
  `stock_id` INT(11) NOT NULL AUTO_INCREMENT,
  `stock_cod` VARCHAR(45) NOT NULL,
  `stock_desc` VARCHAR(45) NOT NULL,
  `stock_tipo_unit` VARCHAR(45) NULL DEFAULT NULL,
  `stock_forn` VARCHAR(45) NULL DEFAULT NULL,
  `stock_inicial` INT(11) NULL DEFAULT NULL,
  `stock_minimo` INT(11) NULL DEFAULT NULL,
  `stock_atual` INT(11) NULL DEFAULT NULL,
  `stock_prec` DECIMAL(7,2) NULL DEFAULT 0.00,
  `stock_obs` LONGTEXT NULL DEFAULT NULL,
  `stock_created` DATETIME NOT NULL,
  `stock_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`stock_id`),
  UNIQUE INDEX `patrimony_id_UNIQUE` (`stock_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela referente a stock';


-- -----------------------------------------------------
-- Table `gclinic`.`unit_type_stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`unit_type_stock` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`unit_type_stock` (
  `tipo_unitario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_unitario` CHAR(20) NOT NULL COMMENT 'Tabela tipo unitario responsavel por armazenar os valores',
  PRIMARY KEY (`tipo_unitario_id`),
  UNIQUE INDEX `tipo_unitario_id_UNIQUE` (`tipo_unitario_id` ASC),
  UNIQUE INDEX `tipo_unitario_UNIQUE` (`tipo_unitario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gclinic`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`users` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_img_profile` VARCHAR(150) NULL DEFAULT NULL,
  `user_name` CHAR(70) CHARACTER SET 'utf8' NOT NULL,
  `user_email` CHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `user_password` CHAR(128) CHARACTER SET 'utf8' NOT NULL,
  `user_session_id` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `user_permissions` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_cpf` CHAR(12) NULL DEFAULT NULL COMMENT 'CPF do usuário.',
  `user_rg` CHAR(23) NULL DEFAULT NULL COMMENT 'RG do usuário.',
  `user_birth` DATE NULL DEFAULT NULL COMMENT 'Data de nascimento do usuário',
  `user_gen` ENUM('Não informado', 'Masculino', 'Feminino') NOT NULL DEFAULT 'Não informado' COMMENT 'Especificação do genero: 1 = Não informado; 2 = Masculino; Feminino  ',
  `user_civil_status` CHAR(25) NULL DEFAULT NULL,
  `user_home_phone` CHAR(12) NULL DEFAULT NULL,
  `user_cel_phone` CHAR(12) NULL DEFAULT NULL,
  `user_father_name` CHAR(70) NULL DEFAULT NULL,
  `user_mother_name` CHAR(70) NULL DEFAULT NULL,
  `user_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_district` CHAR(45) NULL DEFAULT NULL,
  `user_city` CHAR(45) NULL DEFAULT NULL,
  `user_state` CHAR(5) NULL DEFAULT NULL,
  `user_cep` CHAR(25) NULL DEFAULT NULL,
  `user_func_pri` VARCHAR(50) NULL DEFAULT NULL,
  `user_func_sec` VARCHAR(50) NULL DEFAULT NULL,
  `user_date_adm` DATE NULL DEFAULT NULL,
  `user_date_dem` DATE NULL DEFAULT NULL,
  `user_active` INT(11) NOT NULL DEFAULT 0 COMMENT 'Indica se o usuario esta ativo ou não: 0 = Desativado / 1 = Ativo',
  `user_esp1` VARCHAR(45) NULL DEFAULT NULL,
  `user_esp2` VARCHAR(45) NULL DEFAULT NULL,
  `user_esp3` VARCHAR(45) NULL DEFAULT NULL,
  `user_cro` VARCHAR(45) NULL DEFAULT NULL,
  `user_dom1` VARCHAR(45) NULL DEFAULT NULL,
  `user_dom2` VARCHAR(45) NULL DEFAULT NULL,
  `user_seg1` VARCHAR(45) NULL DEFAULT NULL,
  `user_seg2` VARCHAR(45) NULL DEFAULT NULL,
  `user_ter1` VARCHAR(45) NULL DEFAULT NULL,
  `user_ter2` VARCHAR(45) NULL DEFAULT NULL,
  `user_qua1` VARCHAR(45) NULL DEFAULT NULL,
  `user_qua2` VARCHAR(45) NULL DEFAULT NULL,
  `user_qui1` VARCHAR(45) NULL DEFAULT NULL,
  `user_qui2` VARCHAR(45) NULL DEFAULT NULL,
  `user_sex1` VARCHAR(45) NULL DEFAULT NULL,
  `user_sex2` VARCHAR(45) NULL DEFAULT NULL,
  `user_sab1` VARCHAR(45) NULL DEFAULT NULL,
  `user_sab2` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gclinic`.`users_civil_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`users_civil_status` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`users_civil_status` (
  `tipo_unitario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_unitario` CHAR(20) NOT NULL,
  PRIMARY KEY (`tipo_unitario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gclinic`.`users_esp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`users_esp` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`users_esp` (
  `esp_id` INT(11) NOT NULL,
  `esp` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`esp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gclinic`.`users_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gclinic`.`users_permissions` ;

CREATE TABLE IF NOT EXISTS `gclinic`.`users_permissions` (
  `permissions_id` CHAR(11) NOT NULL,
  `permissions` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`permissions_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
